sudo: required
services:
  - docker

before_install:
  - docker build -t pavan26devops/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pavan26devops/docker-react npm run test -- --coverage 
